### PR TITLE
Fix email body not displaying in Outlook 2010

### PR DESCRIPTION
**Pull request by stphnnnn**
I've removed the empty subject parameter from the email sharer which was causing the subject of the created email to be "&body=" in some email clients (Outlook 2010) and for the actual body not to be displayed.

I've tested in a number of other email clients to ensure that this doesn't cause any unwanted side effects but I'm not sure if this was deliberate and I'm missing something 🙃 

What do you think?

### CODE REVIEW

**Comment by avdeev** [comment]
@stphnnnn I dont know. But i can bump the major version :)

I think we can do a little research.

**Comment by avdeev** [comment]
@stphnnnn MDN agrees with you. :)`subject` is not required param.

Can you change unit tests?

**Comment by stphnnnn** [comment]
Brilliant! Tests updated :)

**Comment by avdeev** [comment]
@stphnnnn Released!

**Pull request merged**
