### PR TITLE
feat: whatsapp api update

### PR DESCRIPTION
**Pull request by zalog**
I think we can use [whatsapp api](https://faq.whatsapp.com/en/android/26000030/?category=5245251).
Tested on android and web chrome.

### CODE REVIEW

**Comment by avdeev** [comment]
@zalog Thanks!
Very good new API
Can you update tests and use window.open instead of mobileShare helper?

**Comment by zalog** [comment]
Oh! Missed that, it was a quick pr made directly on github.
I can validate the tests today :)

**Comment by zalog** [comment]
Back! Please take a look now.

**Comment by avdeev** [comment]
@zalog Thanks!
I will prepare docs and demo, and then I'll release

**Comment by zalog** [comment]
Great! I'll keep an eye on you.
You have a star :)

**Comment by avdeev** [comment]
@zalog I released package with new Whatsapp API
You can help with testing and new popular sharers. :)

**Comment by zalog** [comment]
Oh, you added phone! 👍

**Comment by avdeev** [comment]
Yes.
I decided not to change the original interface much.
Although this is not a useful parameter for sharing.

**Comment by zalog** [comment]
Yes, It's not.
But I have projects that need "send me a whatsapp message", and we have covered this case too, witch is great. Especially that is about a simple parameter, so it's effortless.

**Pull request merged**
